name: 'Helios Security Test'
description: 'Checks availability of helios.se.ifmo.ru logins in your Java code.'
author: 'Kamil Chulakov'
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cloning repo
      run: git clone https://github.com/ulyanovskk/helios-security.git
    - name: Build with Maven
      run: mvn -B package --file helios-security/pom.xml
      
      
branding:
  icon: 'check-square'
  color: 'gray-dark'
